#!/usr/bin/env python3
# checking system health
import datetime
import psutil
# Get current time and date
current_time = datetime.datetime.now()
print("Current Time and Date:", current_time.strftime("%Y-%m-%d %H:%M:%S"))
print("################################################################################")

#Checking Memory usage and alert if usage is above 80%
import psutil
memory = psutil.virtual_memory()
total = memory.total // (1024 * 1024)
used = memory.used // (1024 * 1024)
free = memory.available // (1024 * 1024) 
print(f"Memory Usage: Total={total}MB, Used={used}MB, Free={free}MB")
if memory.percent > 80:
    print(f"Alert: Memory usage is above 80%. Current usage is {memory.percent}%")
else:
    print(f"Memory usage is within limits. Current usage is {memory.percent}%") 
print("################################################################################")

#Checking CPU usage and alert if usage is above 80%
cpu_usage = psutil.cpu_percent(interval=1)
print(f"CPU Usage: {cpu_usage}%")
if cpu_usage > 80:
    print(f"Alert: CPU usage is above 80%. Current usage is {cpu_usage}%")
else:          
    print(f"CPU usage is within limits. Current usage is {cpu_usage}%")
print("################################################################################")       

#Checking Disk usage and alert if usage is above 80%
disk = psutil.disk_usage('/')
total_disk = disk.total // (1024 * 1024 * 1024)
used_disk = disk.used // (1024 * 1024 * 1024)
free_disk = disk.free // (1024 * 1024 * 1024)
print(f"Disk Usage: Total={total_disk}GB, Used={used_disk}GB, Free={free_disk}GB")
if disk.percent > 80:
    print(f"Alert: Disk usage is above 80%. Current usage is {disk.percent}%")
else:
    print(f"Disk usage is within limits. Current usage is {disk.percent}%")
print("################################################################################")       